GET http://localhost:8080/signup
Accept: application/json

###

GET http://localhost:8080/
Accept: application/json
Authorization: Basic am9obmRvZUBkb21haW4uZG9tYWluOnBhc3N3b3Jk

###

POST http://localhost:8080/signup
Accept: application/json
Content-Type: application/json

{
  "id": 0,
  "email": "johndoe@domain.domain",
  "password": "password",
  "firstName": "john",
  "lastName": "doe"
}

###

